
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manyoTask_development


test:
  <<: *default
  database: manyoTask_test


production:
  <<: *default
  database: manyoTask_production
  username: manyoTask
  password: <%= ENV['MANYOTASK_DATABASE_PASSWORD'] %>
